# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: efb4123a3f7e8c2e9faf2bd461740bb92a68b590884e462286a13f25f600638318e3322482aa9fb192d470ed28fbb45b357617f1089c8e85fc89828831d5504a

test:
  secret_key_base: 67ea865c7e06a974f09b0aa8e60f970ed8b573a376c87e4197e6b41b5ad260757bf070cb581e64fa8f29f95a5da8b8116dfff829ed9841f3d85f309d12a7dde3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
